apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaling-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaling-hpa
  template:
    metadata:
      labels:
        app: autoscaling-hpa
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: "25m"
          limits:
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: autoscaling-hpa
  labels:
    app: autoscaling-hpa
spec:
  ports:
  - port: 80
  selector:
    app: autoscaling-hpa
