apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: intranet
  namespace: metallb-system
spec:
  addresses:
    - 192.168.56.10-192.168.56.99
  avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: layer2-intranet
  namespace: metallb-system
spec:
  ipAddressPools:
    - intranet
