apiVersion: v1
kind: Namespace
metadata:
  name: limit-range-basic
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-basic
  namespace: limit-range-basic
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "256Mi"
    defaultRequest:
      cpu: "250m"
      memory: "128Mi"
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-limit-range-basic
  namespace: limit-range-basic
spec:
  containers:
  - name: demo
    image: busybox
    command: ["sleep", "3600"]
