apiVersion: v1
kind: Namespace
metadata:
  name: limit-range-basic-minimal-constraints
---
apiVersion: v1
kind: LimitRange
metadata:
  name: range-limits
  namespace: limit-range-basic-minimal-constraints
spec:
  limits:
  - min:
      cpu: "100m"
      memory: "64Mi"
    max:
      cpu: "500m"
      memory: "500Mi"
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-limit-range-basic-minimal-constraints
  namespace: limit-range-basic-minimal-constraints
spec:
  containers:
  - name: demo
    image: busybox
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: "501m"
        memory: "501Mi"
