apiVersion: v1
kind: Namespace
metadata:
  name: limit-range-pod
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-pod
  namespace: limit-range-pod
spec:
  limits:
  - max:
      cpu: "1"
      memory: "1Gi"
    type: Pod
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-limit-range-pod
  namespace: limit-range-pod
spec:
  containers:
  - name: demo
    image: busybox
    command: ["sleep", "3600"]
    resources:

